Multifinger\AppSettingsBundle\Entity\Setting:
    type:                           entity
    table:                          multi__app_settings__setting
    repositoryClass:                Multifinger\AppSettingsBundle\Repository\SettingRepository
    fields:
        name:                       { type: string, length: 255, id: true }
        value:                      { type: text }
        description:                { type: string, length: 1024 }
    lifecycleCallbacks:             {  }
