services:

    multifinger.settings:
        class:                      Multifinger\SettingsBundle\Service\SettingsService
        arguments:                  ['@doctrine.orm.default_entity_manager']
