services:

    Multifinger\SettingsBundle\Service\SettingsService:
        class:                      Multifinger\SettingsBundle\Service\SettingsService
        arguments:                  ['@doctrine']
