<?php

namespace Multifinger\AppSettingsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Maksim Borisov <maksim.i.borisov@gmail.com> 25.04.17 17:49
 */
class SettingRepository extends EntityRepository
{

    /** Maximum query limit */
    const MAX_LIMIT = 1000;

    /**
     * @param int $limit  limit
     * @param int $offset offset
     *
     * @return mixed
     */
    public function getNames($limit, $offset = 0)
    {
        $query = $this->getQueryBuilder($limit, $offset)->select('o.name')->getQuery();

        $result = $query->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        $names = array();
        foreach ($result as & $value) {
            $names[]=$value['name'];
        }

        return $names;
    }

    /**
     * @param int $limit  limit
     * @param int $offset offset
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilder($limit, $offset = 0)
    {
        $qb = $this->createQueryBuilder('o');

        $qb->setMaxResults(min($limit, self::MAX_LIMIT));

        if ($offset) {
            $qb->setFirstResult($offset);
        }

        $qb->orderBy('o.name', 'ASC');

        return $qb;
    }

}
