<?php

namespace Multifinger\SettingsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Maksim Borisov <maksim.i.borisov@gmail.com> 16.03.2020 19:16
 */
class SettingRepository extends EntityRepository
{

    /** Maximum query limit */
    const int MAX_LIMIT = 1000;

    public function getNames(int $limit, int $offset = 0): array
    {
        $query = $this->getQueryBuilder($limit, $offset)->select('o.name')->getQuery();

        $result = $query->getResult(Query::HYDRATE_ARRAY);

        $names = array();
        foreach ($result as & $value) {
            $names[]=$value['name'];
        }

        return $names;
    }

    public function getQueryBuilder(int $limit, int $offset = 0): QueryBuilder
    {
        $qb = $this->createQueryBuilder('o');

        $qb->setMaxResults(min($limit, self::MAX_LIMIT));

        if ($offset) {
            $qb->setFirstResult($offset);
        }

        $qb->orderBy('o.name', 'ASC');

        return $qb;
    }

}
